name: Run github actions with labeler

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: setup-note
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - id: label-the-PR
        uses: actions/labeler@v4

      - id: run-normal-tests
        if: contains(steps.label-the-PR.outputs.all-labels, 'normal')
        run: |
          echo "Running normal tests..."
          # Put your commands for running frontend tests here

      - id: run-backend-tests
        if: contains(steps.label-the-PR.outputs.all-labels, 'un-happy')
        run: |
          echo "Running un-happy tests..."
          # Put your commands for running backend tests here